# Generated by Django 5.2.13 on 2026-05-10 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_remove_propertyimage_created_at_property_capacity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'ordering': ['id']},
        ),
    ]
